#!/bin/bash

NOTEPATH="$HOME/.config/crabnotes"
NOTEFILE="$NOTEPATH/notes.md"
# Create files if not exists
mkdir -p ~/.config
mkdir -p ~/.config/crabnotes
touch ${NOTEFILE}

case "$1" in
    # Search notes
    "")
        if [ -s ${NOTEFILE} ]
        then
            LINE=$(grep -hr ^# ${NOTEPATH} | fzf)
            if ! [ -z "$LINE" ]
            then
                NOTE=$(cat ${NOTEPATH}/* | sed -n "/${LINE}/,/^#/p" | sed "\${/# /d;}" | sed -e :a -e '/./,$!d;/^\n*$/{$d;N;};/\n$/ba')
                echo "${NOTE}" | bat -l md --highlight-line 1 --style snip
                exit 0
            else
                echo "No notes found for that query."
                exit 1
            fi
        else
            echo "Notes file is empty. (Edit with \"cnotes edit\")"
        fi
    ;;
    # Edit notes
    "edit")
        echo "Editing notes file."
        $EDITOR ${NOTEFILE}
        exit 0
    ;;
    # Wrong command
    "add")
        echo "Did you mean \"cnotes edit\"?"
        exit 1
    ;;
    # Unknown command
    *)
        echo "Unknown command."
        exit 1
    ;;
esac
